import sqlite3

# Путь к базе данных Django
DB_PATH = r"C:\Users\user\PycharmProjects\WordScope\WordScope\db.sqlite3"

# Список глаголов
adverbs = [
    ("quickly", "быстро", "She answered the question quickly."),
    ("slowly", "медленно", "The turtle moves slowly."),
    ("well", "хорошо", "He plays the piano well."),
    ("badly", "плохо", "She sang badly at the concert."),
    ("easily", "легко", "You can easily solve this problem."),
    ("hard", "тяжело", "He works hard every day."),
    ("fast", "быстро", "He runs fast."),
    ("loudly", "громко", "She spoke loudly to be heard."),
    ("quietly", "тихо", "Please speak quietly in the library."),
    ("happily", "счастливо", "They lived happily ever after."),
    ("sadly", "грустно", "She looked at him sadly."),
    ("angrily", "сердито", "He shouted angrily at the referee."),
    ("calmly", "спокойно", "She explained the situation calmly."),
    ("carefully", "осторожно", "Handle the glass carefully."),
    ("carelessly", "небрежно", "He drove carelessly and caused an accident."),
    ("clearly", "ясно", "She explained the rules clearly."),
    ("unclearly", "неясно", "He spoke unclearly, so I didn’t understand."),
    ("correctly", "правильно", "Make sure you spell the word correctly."),
    ("incorrectly", "неправильно", "He answered the question incorrectly."),
    ("eagerly", "с нетерпением", "She waited eagerly for the results."),
    ("reluctantly", "неохотно", "He reluctantly agreed to help."),
    ("easily", "легко", "This fabric tears easily."),
    ("difficultly", "с трудом", "He breathed difficultly after the race."),
    ("fluently", "бегло", "She speaks English fluently."),
    ("haltingly", "с запинками", "He spoke haltingly, unsure of his words."),
    ("happily", "счастливо", "The children played happily in the park."),
    ("unhappily", "несчастливо", "She looked at him unhappily."),
    ("honestly", "честно", "He answered all questions honestly."),
    ("dishonestly", "нечестно", "He acted dishonestly during the negotiation."),
    ("frequently", "часто", "She frequently visits her grandparents."),
    ("rarely", "редко", "He rarely eats sweets."),
    ("occasionally", "время от времени", "We occasionally go to the theater."),
    ("always", "всегда", "She always arrives on time."),
    ("never", "никогда", "I never eat meat."),
    ("sometimes", "иногда", "Sometimes I walk to work."),
    ("often", "часто", "They often travel together."),
    ("seldom", "редко", "He seldom complains."),
    ("usually", "обычно", "I usually drink coffee in the morning."),
    ("generally", "как правило", "Generally, people enjoy holidays."),
    ("regularly", "регулярно", "She exercises regularly."),
    ("irregularly", "нерегулярно", "He attends classes irregularly."),
    ("recently", "недавно", "I recently started a new job."),
    ("lately", "в последнее время", "She’s been working hard lately."),
    ("now", "сейчас", "I’m busy now."),
    ("soon", "скоро", "We’ll leave soon."),
    ("later", "позже", "We can discuss this later."),
    ("early", "рано", "She arrived early for the meeting."),
    ("late", "поздно", "He came late to the party."),
    ("immediately", "немдленно", "Call me immediately if there’s a problem."),
    ("eventually", "в конце концов", "He eventually finished his project."),
    ("suddenly", "вдруг", "Suddenly, the lights went out."),
    ("gradually", "постепенно", "The situation gradually improved."),
    ("rapidly", "быстро", "The company is growing rapidly."),
    ("slowly", "медленно", "The old computer works slowly."),
    ("abruptly", "резко", "The car stopped abruptly."),
    ("smoothly", "гладко", "The presentation went smoothly."),
    ("roughly", "грубо/приблизительно", "He treated her roughly."),
    ("gently", "нежно", "She placed the baby gently in the crib."),
    ("violently", "жестоко", "He reacted violently to the criticism."),
    ("peacefully", "мирно", "They resolved the conflict peacefully."),
    ("noisily", "шумно", "The children played noisily in the yard."),
    ("silently", "молча", "She left the room silently."),
    ("loudly", "громко", "The music played loudly at the party."),
    ("softly", "мягко", "She whispered softly in his ear."),
    ("brightly", "ярко", "The sun shone brightly."),
    ("dimly", "тускло", "The room was dimly lit."),
    ("clearly", "ясно", "He explained the concept clearly."),
    ("vaguely", "смутно", "I vaguely remember meeting her."),
    ("accurately", "точно", "He described the event accurately."),
    ("inaccurately", "неточно", "The report was inaccurately written."),
    ("precisely", "точно", "Measure the ingredients precisely."),
    ("imprecisely", "неточно", "He spoke imprecisely about the details."),
    ("correctly", "правильно", "Make sure to fill out the form correctly."),
    ("incorrectly", "неправильно", "The address was written incorrectly."),
    ("properly", "правильно", "Make sure the machine is properly installed."),
    ("improperly", "неправильно", "The equipment was improperly used."),
    ("neatly", "аккуратно", "She folded the clothes neatly."),
    ("messily", "неряшливо", "He ate messily, spilling food everywhere."),
    ("tidy", "опрятно", "The room was tidy and clean."),
    ("clumsily", "неловко", "He clumsily dropped the glass."),
    ("gracefully", "изящно", "She danced gracefully across the stage."),
    ("awkwardly", "неловко", "He awkwardly tried to apologize."),
    ("confidently", "уверенно", "She spoke confidently during the presentation."),
    ("nervously", "нервно", "He waited nervously for the results."),
    ("proudly", "с гордостью", "She proudly showed her award."),
    ("humble", "скромно", "He spoke humbly about his achievements."),
    ("boldly", "смело", "He boldly stood up for his beliefs."),
    ("timidly", "робко", "She timidly asked for help."),
    ("courageously", "храбро", "The firefighter acted courageously."),
    ("cowardly", "трусливо", "He cowardly refused to take responsibility."),
    ("wisely", "мудро", "She wisely invested her savings."),
    ("foolishly", "глупо", "He foolishly ignored the warnings."),
    ("intelligently", "умно", "She answered the question intelligently."),
    ("stupidly", "глупо", "He stupidly left his keys in the car."),
    ("politely", "вежливо", "He politely asked for directions."),
    ("rudely", "грубо", "She rudely interrupted the conversation."),
    ("kindly", "добро", "She kindly offered her help."),
    ("cruelly", "жестоко", "He was cruelly treated by his boss."),
    ("generously", "щедро", "He generously donated to charity."),
    ("stingily", "скупо", "She stingily refused to share."),
    ("happily", "счастливо", "They chatted happily for hours."),
    ("unhappily", "несчастливо", "He sighed unhappily."),
    ("excitedly", "с волнением", "The children talked excitedly about the trip."),
    ("calmly", "спокойно", "She calmly explained her side of the story."),
    ("anxiously", "тревожно", "He waited anxiously for the news."),
    ("patiently", "терпеливо", "She patiently waited for her turn."),
    ("impatiently", "нетерпеливо", "He tapped his fingers impatiently."),
    ("eagerly", "с нетерпением", "She eagerly opened her birthday present."),
    ("reluctantly", "неохотно", "He reluctantly agreed to the plan."),
    ("willingly", "охотно", "She willingly helped with the project."),
    ("unwillingly", "неохотно", "He unwillingly admitted his mistake."),
    ("enthusiastically", "с энтузиазмом", "She enthusiastically supported the idea."),
    ("indifferently", "равнодушно", "He responded indifferently to the news."),
    ("passionately", "страстно", "She spoke passionately about her beliefs."),
    ("coldly", "холодно", "He coldly rejected the offer."),
    ("warmly", "тепло", "She warmly greeted her guests."),
    ("friendly", "дружелюбно", "The dog wagged its tail friendly."),
    ("hostilely", "враждебно", "He looked at her hostilely."),
    ("lovingly", "с любовью", "She lovingly hugged her child."),
    ("hatefully", "с ненавистью", "He glared at her hatefully."),
    ("jealously", "ревниво", "She watched them jealously."),
    ("proudly", "с гордостью", "He proudly displayed his trophy."),
    ("shyly", "застенчиво", "She shyly smiled at him."),
    ("confidently", "уверенно", "He confidently presented his project."),
    ("doubtfully", "сомневаясь", "She looked at him doubtfully."),
    ("suspiciously", "подозрительно", "He eyed her suspiciously."),
    ("truthfully", "правдиво", "She answered truthfully all the questions."),
    ("deceptively", "обманчиво", "The situation looked deceptively simple."),
    ("openly", "открыто", "She openly expressed her opinion."),
    ("secretly", "тайно", "They met secretly to discuss the plan."),
    ("publicly", "публично", "He publicly apologized for his mistake."),
    ("privately", "конфиденциально", "She spoke to him privately."),
    ("formally", "официально", "He was formally dressed for the event."),
    ("informally", "неофициально", "They chatted informally over coffee."),
    ("casually", "небрежно", "He casually mentioned his achievement."),
    ("seriously", "серьёзно", "She took the matter seriously."),
    ("jokingly", "шутливо", "He jokingly suggested they quit their jobs."),
    ("playfully", "игриво", "The kitten playfully chased its tail."),
    ("aggressively", "агрессивно", "He aggressively defended his position."),
    ("passively", "пассивно", "She passively watched the argument."),
    ("actively", "активно", "He actively participates in discussions."),
    ("lazily", "лениво", "He lazily stretched on the couch."),
    ("energetically", "энергично", "She energetically led the workout."),
    ("tirelessly", "неутомимо", "He worked tirelessly on the project."),
    ("wearily", "устало", "She wearily rubbed her eyes."),
    ("eagerly", "с нетерпением", "The kids eagerly awaited the trip."),
    ("reluctantly", "неохотно", "He reluctantly agreed to the change."),
    ("willingly", "охотно", "She willingly took on the extra work."),
    ("grudgingly", "неохотно", "He grudgingly admitted he was wrong."),
    ("cheerfully", "весело", "She cheerfully greeted everyone."),
    ("gloomily", "мрачно", "He stared gloomily out the window."),
    ("hopefully", "с надеждой", "She looked at him hopefully."),
    ("despairingly", "отчаянно", "He shook his head despairingly."),
    ("optimistically", "оптимистично", "She spoke optimistically about the future."),
    ("pessimistically", "пессимистично", "He viewed the situation pessimistically."),
    ("realistically", "реалистично", "We need to think realistically."),
    ("unrealistically", "нереалистично", "His expectations were unrealistically high."),
    ("practically", "практично", "She dressed practically for the hike."),
    ("impractically", "непрактично", "He packed impractically for the trip."),
    ("logically", "логично", "She explained her decision logically."),
    ("illogically", "нелогично", "He argued illogically."),
    ("rationally", "рационально", "We need to act rationally."),
    ("irrationally", "иррационально", "He reacted irrationally to the news."),
    ("sensibly", "разумно", "She sensibly saved her money."),
    ("nonsensically", "бессмысленно", "He rambled nonsensically."),
    ("wisely", "мудро", "He wisely chose to wait."),
    ("foolishly", "глупо", "He foolishly ignored the advice."),
    ("brilliantly", "блестяще", "She performed brilliantly in the concert."),
    ("poorly", "плохо", "The team played poorly in the first half."),
    ("adequately", "удовлетворительно", "He was adequately prepared for the test."),
    ("inadequately", "неудовлетворительно", "The issue was inadequately addressed."),
    ("thoroughly", "тщательно", "She thoroughly cleaned the house."),
    ("superficially", "поверхностно", "He only superficially understood the topic."),
    ("deeply", "глубоко", "She was deeply moved by the speech."),
    ("shallowly", "поверхностно", "He thought shallowly about the consequences."),
    ("completely", "полностью", "She completely forgot about the meeting."),
    ("partially", "частично", "The work is only partially finished."),
    ("fully", "полностью", "The tank is fully loaded."),
    ("barely", "едва", "He barely passed the exam."),
    ("scarcely", "едва", "She scarcely had time to eat."),
    ("hardly", "едва", "I hardly recognized him after all these years."),
    ("almost", "почти", "We’re almost there."),
    ("nearly", "почти", "The project is nearly completed."),
    ("entirely", "полностью", "The story was entirely false."),
    ("totally", "полностью", "I totally agree with you."),
    ("absolutely", "абсолютно", "She is absolutely right."),
    ("completely", "полностью", "He completely misunderstood the instructions."),
    ("partly", "частично", "The success was partly due to luck."),
    ("somewhat", "в какой-то степени", "The movie was somewhat boring."),
    ("slightly", "слегка", "The door was slightly open."),
    ("barely", "едва", "He barely made it on time."),
    ("just", "только что", "He just left the office."),
    ("already", "уже", "She has already finished her homework."),
    ("still", "всё ещё", "He is still working on the project."),
    ("yet", "ещё (в отрицаниях/вопросах)", "Have you finished yet?"),
    ("even", "даже", "He didn’t even try to help."),
    ("only", "только", "She only ate a small piece."),
    ("merely", "просто", "It was merely a misunderstanding."),
    ("simply", "просто", "She simply refused to go."),
    ("basically", "в основном", "Basically, we need more time."),
    ("essentially", "по сути", "Essentially, they agree on the main points."),
    ("fundamentally", "фундаментально", "Their views are fundamentally different."),
    ("primarily", "преимущественно", "The book is primarily for beginners."),
    ("mainly", "главным образом", "The problem is mainly financial."),
    ("largely", "в значительной степени", "The success was largely due to teamwork."),
    ("partially", "частично", "The damage was partially repaired."),
    ("somewhat", "в какой-то степени", "The task was somewhat difficult."),
    ("slightly", "слегка", "The temperature dropped slightly."),
    ("considerably", "значительно", "The price increased considerably."),
    ("significantly", "значительно", "The results improved significantly."),
    ("dramatically", "резко", "The situation changed dramatically."),
    ("radically", "радикально", "His views changed radically over time."),
    ("moderately", "умеренно", "The climate here is moderately warm."),
    ("extremely", "крайне", "The test was extremely difficult."),
    ("highly", "очень", "She is highly qualified for the job."),
    ("intensely", "интенсивно", "He worked intensely on the project."),
    ("strongly", "сильно", "She strongly disagreed with the proposal."),
    ("weakly", "слабо", "He weakly protested the decision."),
    ("firmly", "твёрдо", "She firmly believed in her ideas."),
    ("loosely", "свободно", "The knot was loosely tied."),
    ("tightly", "плотно", "She tightly closed the lid."),
    ("securely", "надёжно", "The documents were securely locked."),
    ("insecurely", "ненадёжно", "The shelf was insecurely attached."),
    ("safely", "безопасно", "Drive safely on the icy roads."),
    ("dangerously", "опасно", "He drove dangerously fast."),
    ("comfortably", "удобно", "She sat comfortably in the armchair."),
    ("uncomfortably", "неудобно", "He shifted uncomfortably in his seat."),
    ("cozily", "уютно", "The room was cozily decorated."),
    ("spaciously", "просторно", "The apartment was spaciously designed."),
    ("crampedly", "тесно", "They lived crampedly in the small apartment."),
    ("neatly", "аккуратно", "The books were neatly arranged."),
    ("messily", "неряшливо", "He ate messily, spilling food everywhere."),
    ("orderly", "упорядоченно", "The files were orderly organized."),
    ("chaotically", "хаотично", "The children ran chaotically around the room."),
    ("systematically", "систематически", "She systematically reviewed the data."),
    ("randomly", "случайно", "The names were selected randomly."),
    ("methodically", "методично", "He methodically solved each problem."),
    ("haphazardly", "бессистемно", "The tools were haphazardly scattered."),
    ("efficiently", "эффективно", "The team worked efficiently."),
    ("inefficiently", "неэффективно", "The old machine operated inefficiently."),
    ("productively", "продуктивно", "They worked productively all day."),
    ("unproductively", "непродуктивно", "The meeting ended unproductively."),
    ("effectively", "эффективно", "She communicated her ideas effectively."),
    ("ineffectively", "неэффективно", "The policy was implemented ineffectively."),
    ("successfully", "успешно", "He successfully completed the mission."),
    ("unsuccessfully", "неуспешно", "They unsuccessfully tried to negotiate."),
    ("easily", "легко", "The software installs easily."),
    ("with difficulty", "с трудом", "He climbed the mountain with difficulty."),
    ("smoothly", "гладко", "The project proceeded smoothly."),
    ("roughly", "грубо/приблизительно", "He roughly estimated the cost."),
    ("accurately", "точно", "She accurately predicted the outcome."),
    ("inaccurately", "неточно", "The data was recorded inaccurately."),
    ("precisely", "точно", "Measure the ingredients precisely."),
    ("imprecisely", "неточно", "He spoke imprecisely about the timeline."),
    ("exactly", "точно", "The train arrived exactly on time."),
    ("approximately", "приблизительно", "The distance is approximately 10 kilometers."),
    ("nearly", "почти", "The task is nearly completed."),
    ("almost", "почти", "We’re almost there."),
    ("barely", "едва", "He barely passed the test."),
    ("scarcely", "едва", "She scarcely had time to prepare."),
    ("hardly", "едва", "I hardly noticed the difference."),
    ("just", "только что", "He just called me."),
    ("only", "только", "She only ate a sandwich."),
    ("merely", "всего лишь", "It was merely a suggestion."),
    ("simply", "просто", "She simply ignored the warning."),
    ("literally", "буквально", "He literally ran all the way home."),
    ("figuratively", "в переносном смысле", "She figuratively exploded with anger."),
    ("technically", "технически", "Technically, the project is finished."),
    ("practically", "практически", "The work is practically done."),
    ("theoretically", "теоретически", "Theoretically, it should work."),
    ("financially", "финансово", "They are financially stable."),
    ("emotionally", "эмоционально", "She reacted emotionally to the news."),
    ("physically", "физически", "He is physically strong."),
    ("mentally", "умственно", "The task was mentally challenging."),
    ("socially", "социально", "She is socially active."),
    ("culturally", "культурно", "The festival is culturally significant."),
    ("historically", "исторически", "This building is historically important."),
    ("geographically", "географически", "The regions are geographically diverse."),
    ("politically", "политически", "The decision was politically motivated."),
    ("economically", "экономически", "The country is economically developed."),
    ("environmentally", "с точки зрения экологии", "The project is environmentally friendly."),
    ("scientifically", "научно", "The theory is scientifically proven."),
    ("artistically", "художественно", "She is artistically talented."),
    ("musically", "музыкально", "He is musically gifted."),
    ("linguistically", "лингвистически", "The languages are linguistically related."),
    ("mathematically", "математически", "The problem is mathematically complex."),
    ("logically", "логически", "The argument is logically sound."),
    ("philosophically", "философски", "They discussed the issue philosophically."),
    ("psychologically", "психологически", "He is psychologically prepared."),
    ("biologically", "биологически", "The species are biologically distinct."),
    ("chemically", "химически", "The substances are chemically similar."),
    ("physically", "физически", "The task is physically demanding."),
    ("naturally", "естественно", "She naturally excels in sports."),
    ("artificially", "искусственно", "The flavor is artificially enhanced."),
    ("automatically", "автоматически", "The door closes automatically."),
    ("manually", "вручную", "The data was entered manually."),
    ("digitally", "цифровым способом", "The files are stored digitally."),
    ("analogously", "аналогично", "The situations are analogously structured."),
    ("symbolically", "символически", "The gesture was symbolically important."),
    ("literally", "буквально", "He literally worked day and night."),
    ("metaphorically", "метафорически", "She spoke metaphorically about life."),
    ("ironically", "иронично", "Ironically, he failed the test on irony."),
    ("sarcastically", "саркастически", "She replied sarcastically to his comment."),
    ("humorously", "с юмором", "He told the story humorously."),
    ("seriously", "серьёзно", "She took the matter seriously."),
    ("playfully", "игриво", "The puppy playfully chased its tail."),
    ("mockingly", "насмешливо", "He mockingly imitated her voice."),
    ("sincerely", "искренне", "She sincerely apologized for her mistake."),
    ("insincerely", "неискренне", "He insincerely complimented her work."),
    ("genuinely", "по-настоящему", "She genuinely cared about others."),
    ("falsely", "ложно", "He was falsely accused of the crime."),
    ("truthfully", "правдиво", "She answered truthfully all the questions."),
    ("deceptively", "обманчиво", "The task looked deceptively simple."),
    ("openly", "открыто", "She openly expressed her opinion."),
    ("secretly", "тайно", "They secretly planned the surprise party."),
    ("publicly", "публично", "He publicly announced his resignation."),
    ("privately", "конфиденциально", "She privately shared her concerns."),
    ("confidentially", "конфиденциально", "He spoke to her confidentially."),
    ("anonymously", "анонимно", "The letter was sent anonymously."),
    ("collectively", "коллективно", "They worked collectively on the project."),
    ("individually", "индивидуально", "Each student was assessed individually."),
    ("jointly", "совместно", "The companies jointly developed the product."),
    ("separately", "отдельно", "The ingredients are packaged separately."),
    ("together", "вместе", "They walked together to school."),
    ("apart", "отдельно", "They live apart now."),
    ("alone", "одиноко", "She prefers to work alone."),
    ("singly", "поодиночке", "The tasks were completed singly."),
    ("unitedly", "единодушно", "They unitedly supported the decision."),
    ("dividedly", "раздельно", "The group was dividedly opinionated."),
    ("cooperatively", "сотрудничая", "They worked cooperatively on the task."),
    ("competitively", "соревнуясь", "The teams played competitively."),
    ("collaboratively", "в сотрудничестве", "The project was developed collaboratively."),
    ("independently", "независимо", "She works independently on her research."),
    ("dependently", "в зависимости", "The results varied dependently on the conditions."),
    ("actively", "активно", "He actively participates in community events."),
    ("passively", "пассивно", "She passively watched the discussion."),
    ("aggressively", "агрессивно", "He aggressively pursued his goals."),
    ("defensively", "оборонительно", "She spoke defensively about her work."),
    ("offensively", "нападающе", "He acted offensively during the debate."),
    ("strategically", "стратегически", "The company expanded strategically."),
    ("tactically", "тактически", "They moved tactically to avoid detection."),
    ("logistically", "логистически", "The event was logistically challenging."),
    ("financially", "финансово", "The project is financially supported."),
    ("economically", "экономически", "The policy is economically beneficial."),
    ("socially", "социально", "She is socially active in her community."),
    ("culturally", "культурно", "The festival is culturally diverse."),
    ("environmentally", "с точки зрения экологии", "The product is environmentally safe."),
    ("globally", "глобально", "The company operates globally."),
    ("locally", "местно", "The ingredients are sourced locally."),
    ("regionally", "регионально", "The dialect varies regionally."),
    ("nationally", "на национальном уровне", "The policy was implemented nationally."),
    ("internationally", "на международном уровне", "The agreement was recognized internationally."),
    ("universally", "повсеместно", "The law is universally accepted."),
    ("personally", "лично", "I personally believe in this cause."),
    ("professionally", "профессионально", "She handled the situation professionally."),
    ("academically", "академически", "The paper is academically rigorous."),
    ("scientifically", "научно", "The theory is scientifically proven."),
    ("artistically", "художественно", "She is artistically talented."),
    ("musically", "музыкально", "He is musically inclined."),
    ("athletically", "спортивно", "She is athletically gifted."),
    ("technologically", "технологически", "The company is technologically advanced."),
    ("digitally", "цифровым способом", "The files are stored digitally."),
    ("analogously", "аналогично", "The systems function analogously."),
    ("symbolically", "символически", "The gesture was symbolically significant."),
    ("literally", "буквально", "He literally ran a marathon."),
    ("figuratively", "в переносном смысле", "She figuratively exploded with joy."),
    ("directly", "прямо", "He directly addressed the issue."),
    ("indirectly", "косвенно", "She indirectly hinted at the problem."),
    ("explicitly", "явно", "The rules were explicitly stated."),
    ("implicitly", "подразумеваемо", "The meaning was implicitly understood."),
    ("openly", "открыто", "She openly shared her thoughts."),
    ("secretly", "тайно", "They secretly planned the surprise."),
    ("publicly", "публично", "He publicly announced his decision."),
    ("privately", "конфиденциально", "She privately discussed the matter."),
    ("formally", "официально", "He was formally dressed for the event."),
    ("informally", "неофициально", "They chatted informally over coffee."),
    ("casually", "небрежно", "He casually mentioned his achievement."),
    ("seriously", "серьёзно", "She took the situation seriously."),
    ("jokingly", "шутливо", "He jokingly suggested they quit their jobs."),
    ("sarcastically", "саркастически", "She replied sarcastically to his comment."),
    ("ironically", "иронично", "Ironically, he forgot his own birthday."),
    ("humorously", "с юмором", "He told the story humorously."),
    ("playfully", "игриво", "The kitten playfully chased its tail."),
    ("mockingly", "насмешливо", "He mockingly imitated her voice."),
    ("sincerely", "искренне", "She sincerely apologized for her mistake."),
    ("insincerely", "неискренне", "He insincerely complimented her work."),
    ("genuinely", "по-настоящему", "She genuinely cared about others."),
    ("falsely", "ложно", "He was falsely accused of the crime."),
    ("truthfully", "правдиво", "She answered truthfully all the questions."),
    ("deceptively", "обманчиво", "The task looked deceptively simple."),
    ("honestly", "честно", "He honestly admitted his mistake."),
    ("dishonestly", "нечестно", "He acted dishonestly during the negotiation."),
    ("loyally", "верно", "The dog followed its owner loyally."),
    ("disloyally", "неверно", "He acted disloyally toward his friends."),
    ("faithfully", "преданно", "She faithfully supported her husband."),
    ("unfaithfully", "неверно", "He behaved unfaithfully in the relationship."),
    ("proudly", "с гордостью", "She proudly displayed her award."),
    ("humbly", "скромно", "He humbly accepted the praise."),
    ("boldly", "смело", "He boldly expressed his opinion."),
    ("timidly", "робко", "She timidly asked for help."),
    ("courageously", "храбро", "The firefighter acted courageously."),
    ("cowardly", "трусливо", "He cowardly refused to take responsibility."),
    ("wisely", "мудро", "She wisely invested her savings."),
    ("foolishly", "глупо", "He foolishly ignored the warnings."),
    ("intelligently", "умно", "She intelligently solved the problem."),
    ("stupidly", "глупо", "He stupidly left his keys in the car."),
    ("brilliantly", "блестяще", "She performed brilliantly in the concert."),
    ("poorly", "плохо", "The team played poorly in the first half."),
    ("adequately", "удовлетворительно", "He was adequately prepared for the test."),
    ("inadequately", "неудовлетворительно", "The issue was inadequately addressed."),
    ("thoroughly", "тщательно", "She thoroughly cleaned the house."),
    ("superficially", "поверхностно", "He only superficially understood the topic."),
    ("deeply", "глубоко", "She was deeply moved by the speech."),
    ("shallowly", "поверхностно", "He thought shallowly about the consequences."),
    ("completely", "полностью", "She completely forgot about the meeting."),
    ("partially", "частично", "The work is only partially finished."),
    ("fully", "полностью", "The tank is fully loaded."),
    ("barely", "едва", "He barely passed the exam."),
    ("scarcely", "едва", "She scarcely had time to eat."),
    ("hardly", "едва", "I hardly recognized him after all these years."),
    ("almost", "почти", "We’re almost there."),
    ("nearly", "почти", "The project is nearly completed."),
    ("entirely", "полностью", "The story was entirely false."),
    ("totally", "полностью", "I totally agree with you."),
    ("absolutely", "абсолютно", "She is absolutely right."),
    ("utterly", "совершенно", "The room was utterly dark."),
    ("wholly", "полностью", "The decision was wholly unexpected."),
    ("partly", "частично", "The success was partly due to luck."),
    ("somewhat", "в какой-то степени", "The movie was somewhat boring."),
    ("slightly", "слегка", "The door was slightly open."),
    ("somewhat", "отчасти", "His answer was somewhat unclear."),
    ("rather", "достаточно", "The task was rather difficult."),
    ("quite", "довольно", "She is quite talented."),
    ("fairly", "достаточно", "The weather is fairly nice today."),
    ("extremely", "крайне", "The test was extremely difficult."),
    ("highly", "очень", "She is highly qualified for the job."),
    ("intensely", "интенсивно", "He worked intensely on the project."),
    ("strongly", "сильно", "She strongly disagreed with the proposal."),
    ("weakly", "слабо", "He weakly protested the decision."),
    ("firmly", "твёрдо", "She firmly believed in her ideas."),
    ("loosely", "свободно", "The knot was loosely tied."),
    ("tightly", "плотно", "She tightly closed the lid."),
    ("securely", "надёжно", "The documents were securely locked."),
    ("insecurely", "ненадёжно", "The shelf was insecurely attached."),
    ("safely", "безопасно", "Drive safely on the icy roads."),
    ("dangerously", "опасно", "He drove dangerously fast."),
    ("comfortably", "удобно", "She sat comfortably in the armchair."),
    ("uncomfortably", "неудобно", "He shifted uncomfortably in his seat."),
    ("cozily", "уютно", "The room was cozily decorated."),
    ("spaciously", "просторно", "The apartment was spaciously designed."),
    ("crampedly", "тесно", "They lived crampedly in the small apartment."),
    ("neatly", "аккуратно", "The books were neatly arranged."),
    ("messily", "неряшливо", "He ate messily, spilling food everywhere."),
    ("orderly", "упорядоченно", "The files were orderly organized."),
    ("chaotically", "хаотично", "The children ran chaotically around the room."),
    ("systematically", "систематически", "She systematically reviewed the data."),
    ("randomly", "случайно", "The names were selected randomly."),
    ("methodically", "методично", "He methodically solved each problem."),
    ("haphazardly", "бессистемно", "The tools were haphazardly scattered."),
    ("efficiently", "эффективно", "The team worked efficiently."),
    ("inefficiently", "неэффективно", "The old machine operated inefficiently."),
    ("productively", "продуктивно", "They worked productively all day."),
    ("unproductively", "непродуктивно", "The meeting ended unproductively."),
    ("effectively", "эффективно", "She communicated her ideas effectively."),
    ("ineffectively", "неэффективно", "The policy was implemented ineffectively."),
    ("successfully", "успешно", "He successfully completed the mission."),
    ("unsuccessfully", "неуспешно", "They unsuccessfully tried to negotiate."),
    ("easily", "легко", "The software installs easily."),
    ("with difficulty", "с трудом", "He climbed the mountain with difficulty."),
    ("smoothly", "гладко", "The project proceeded smoothly."),
    ("roughly", "грубо/приблизительно", "He roughly estimated the cost."),
    ("accurately", "точно", "She accurately predicted the outcome."),
    ("inaccurately", "неточно", "The data was recorded inaccurately."),
    ("precisely", "точно", "Measure the ingredients precisely."),
    ("imprecisely", "неточно", "He spoke imprecisely about the timeline."),
    ("exactly", "точно", "The train arrived exactly on time."),
    ("approximately", "приблизительно", "The distance is approximately 10 kilometers."),
    ("nearly", "почти", "The task is nearly completed."),
    ("almost", "почти", "We’re almost there."),
    ("barely", "едва", "He barely passed the test."),
    ("scarcely", "едва", "She scarcely had time to prepare."),
    ("hardly", "едва", "I hardly noticed the difference."),
    ("just", "только что", "He just called me."),
    ("only", "только", "She only ate a sandwich."),
    ("merely", "всего лишь", "It was merely a suggestion."),
    ("simply", "просто", "She simply ignored the warning."),
    ("literally", "буквально", "He literally ran a marathon."),
    ("figuratively", "в переносном смысле", "She figuratively exploded with joy."),
    ("technically", "технически", "Technically, the project is finished."),
    ("practically", "практически", "The work is practically done."),
    ("theoretically", "теоретически", "Theoretically, it should work."),
    ("financially", "финансово", "They are financially stable."),
    ("emotionally", "эмоционально", "She reacted emotionally to the news."),
    ("physically", "физически", "He is physically strong."),
    ("mentally", "умственно", "The task was mentally challenging."),
    ("socially", "социально", "She is socially active."),
    ("culturally", "культурно", "The festival is culturally significant."),
    ("historically", "исторически", "This building is historically important."),
    ("geographically", "географически", "The regions are geographically diverse."),
    ("politically", "политически", "The decision was politically motivated."),
    ("economically", "экономически", "The country is economically developed."),
    ("environmentally", "с точки зрения экологии", "The project is environmentally friendly."),
    ("scientifically", "научно", "The theory is scientifically proven."),
    ("artistically", "художественно", "She is artistically talented."),
    ("musically", "музыкально", "He is musically gifted."),
    ("linguistically", "лингвистически", "The languages are linguistically related."),
    ("mathematically", "математически", "The problem is mathematically complex."),
    ("logically", "логически", "The argument is logically sound."),
    ("philosophically", "философски", "They discussed the issue philosophically."),
    ("psychologically", "психологически", "He is psychologically prepared."),
    ("biologically", "биологически", "The species are biologically distinct."),
    ("chemically", "химически", "The substances are chemically similar."),
    ("physically", "физически", "The task is physically demanding."),
    ("naturally", "естественно", "She naturally excels in sports."),
    ("artificially", "искусственно", "The flavor is artificially enhanced."),
    ("automatically", "автоматически", "The door closes automatically."),
    ("manually", "вручную", "The data was entered manually."),
    ("digitally", "цифровым способом", "The files are stored digitally."),
    ("analogously", "аналогично", "The situations are analogously structured."),
    ("symbolically", "символически", "The gesture was symbolically important."),
    ("ironically", "иронично", "Ironically, he forgot his own birthday."),
    ("sarcastically", "саркастически", "She replied sarcastically to his comment."),
    ("humorously", "с юмором", "He told the story humorously."),
    ("seriously", "серьёзно", "She took the matter seriously."),
    ("playfully", "игриво", "The puppy playfully chased its tail."),
    ("mockingly", "насмешливо", "He mockingly imitated her voice."),
    ("sincerely", "искренне", "She sincerely apologized for her mistake."),
    ("insincerely", "неискренне", "He insincerely complimented her work."),
    ("genuinely", "по-настоящему", "She genuinely cared about others."),
    ("falsely", "ложно", "He was falsely accused of the crime."),
    ("truthfully", "правдиво", "She answered truthfully all the questions."),
    ("deceptively", "обманчиво", "The task looked deceptively simple."),
    ("honestly", "честно", "He honestly admitted his mistake."),
    ("dishonestly", "нечестно", "He acted dishonestly during the negotiation."),
    ("loyally", "верно", "The dog followed its owner loyally."),
    ("disloyally", "неверно", "He acted disloyally toward his friends."),
    ("faithfully", "преданно", "She faithfully supported her husband."),
    ("unfaithfully", "неверно", "He behaved unfaithfully in the relationship."),
    ("proudly", "с гордостью", "She proudly displayed her award."),
    ("humbly", "скромно", "He humbly accepted the praise."),
    ("boldly", "смело", "He boldly expressed his opinion."),
    ("timidly", "робко", "She timidly asked for help."),
    ("courageously", "храбро", "The firefighter acted courageously."),
    ("cowardly", "трусливо", "He cowardly refused to take responsibility."),
    ("wisely", "мудро", "She wisely invested her savings."),
    ("foolishly", "глупо", "He foolishly ignored the warnings."),
    ("intelligently", "умно", "She intelligently solved the problem."),
    ("stupidly", "глупо", "He stupidly left his keys in the car."),
    ("brilliantly", "блестяще", "She performed brilliantly in the concert."),
    ("poorly", "плохо", "The team played poorly in the first half."),
    ("adequately", "удовлетворительно", "He was adequately prepared for the test."),
    ("inadequately", "неудовлетворительно", "The issue was inadequately addressed."),
    ("thoroughly", "тщательно", "She thoroughly cleaned the house."),
    ("superficially", "поверхностно", "He only superficially understood the topic."),
    ("deeply", "глубоко", "She was deeply moved by the speech."),
    ("shallowly", "поверхностно", "He thought shallowly about the consequences.")
]


# Подключаемся к базе
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Вставляем данные
for eng, ru, example in adverbs:
    cursor.execute("""
        INSERT INTO popular_words_words (eng_word, ru_word, word_type, example)
        VALUES (?, ?, ?, ?)
    """, (eng, ru, "adverbs", example))

# Сохраняем и закрываем
conn.commit()
conn.close()

print(f"✅ Добавлено {len(adverbs)} глаголов в базу данных.")
