# Generated by Django 5.2.6 on 2025-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=100, verbose_name='Английское слово')),
                ('ru_word', models.CharField(max_length=100, verbose_name='Русское слово')),
                ('word_type', models.CharField(max_length=50, verbose_name='Тип слова')),
                ('example', models.TextField(verbose_name='Пример использования')),
            ],
        ),
    ]
